id: P004381
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:16:49.515449
source_metadata:
  id: bdr:W1AC223
  title: དབུ་མ་སྣང་བ།
  author: ''
  volumes:
    20c53bd193414af6b2f7ad2adf5663de:
      image_group_id: I2PD18583
      title: ''
      volume_number: 1
      total_pages: 344
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
